# Generated by Django 3.2.9 on 2021-11-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentTeacherManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
