# Generated by Django 3.2.5 on 2021-11-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentTeacherManagement', '0002_auto_20211126_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
    ]
