# Generated by Django 3.2.5 on 2021-11-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentTeacherManagement', '0003_student_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='gpa',
        ),
    ]
