# Generated by Django 3.2.9 on 2021-11-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentTeacherManagement', '0004_rename_student_id_student_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
