# Generated by Django 3.2.5 on 2021-11-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentTeacherManagement', '0005_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='num_of_course',
            field=models.IntegerField(default=0),
        ),
    ]
