# Generated by Django 3.2.5 on 2021-11-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentTeacherManagement', '0005_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('max_student', models.IntegerField()),
                ('current_student_count', models.IntegerField(default=0)),
                ('professor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentTeacherManagement.teacher')),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentTeacherManagement.student')),
            ],
        ),
    ]
