# Generated by Django 3.2.5 on 2021-11-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
